### ISSUE TITLE
海南数据问题

### ISSUE THREAD

**Issue by songjinya** [BlankerL/DXY-2019-nCoV-Crawler#100]
DXYArea统计数据中，海南省 （2020/3/24  12:29:15 PM） 获取到的几条记录，province_curedCount=168，数据有误。
在丁香园查过发现，这个值应该是162。
海南省在这个时间已经清零了，一共有168的确诊，6名死亡，治愈数目应该是162.
猜测可能是city_curedCount修改导致的。前面十分钟获取到的city_curedCount跟这个时间获取的数据有出入。

**Comment by BlankerL** [comment]
感谢指正。经过检查，错误条目已经移除，应该是丁香园错误更新了数据条目之后又回滚到以前的值导致的。

**Comment by BlankerL** [comment]
未来如果还有其他的异常数据，可以在 #34 中反馈，方便其他人汇总查阅。感谢支持！
