### ISSUE TITLE
Example at bottom of page does not work

### ISSUE THREAD

**Issue by Eddiiie** [BlankerL/DXY-2019-nCoV-Crawler#101]
Hello,
Great work.  I am going through your page here https://lab.isaaclin.cn/nCoV/en   and made it to the bottom!  ha   There are 2 examples -

Examples
1. /nCoV/api/news?num=all&lang=en
Return all news in English.

2. /nCoV/api/news?page=2&num=10&lang=en
Return latest 11 to 20 news in English.

Example 1 -   
num=all   does not work at all.     and  
lang=en  does not work, it comes out in Chinese.

:)

Thank you for your work!!

**Comment by BlankerL** [comment]
So sorry, I forgot to update the documentation! 
1. As DXY stopped maintaining the English news, this project will not feed the English news any more, sorry for that. 
2. As the supporting of pagination came out, `num=all` was no longer supported. 

I recommended you to the [advanced documentation](https://lab.isaaclin.cn/nCoV/advanced), it will be updated automatically as the API being updated.

**Comment by BlankerL** [comment]
I have already fixed the documentation, the supporting of English news are removed. Sorry for that.

**Comment by Eddiiie** [comment]
Thank you!
