### ISSUE TITLE
Isle of Man does not have English translation available

### ISSUE THREAD

**Issue by thomasgravina** [BlankerL/DXY-2019-nCoV-Crawler#102]
`{
locationId: 0,
continentName: "欧洲",
continentEnglishName: "Europe",
countryName: "马恩岛",
countryEnglishName: null,
provinceName: "马恩岛",
provinceEnglishName: null,
provinceShortName: "马恩岛",
currentConfirmedCount: 113,
confirmedCount: 114,
suspectedCount: 0,
curedCount: 0,
deadCount: 1,
comment: "",
cities: null,
updateTime: 1586085510377
}`

**Comment by BlankerL** [comment]
Thank you for the report! I have fixed it!
