### ISSUE TITLE
请求rumors 跨域被拦截

### ISSUE THREAD

**Issue by Galileo01** [BlankerL/DXY-2019-nCoV-Crawler#103]
请求rumors， 跨域被拦截怎么办呀

**Comment by BlankerL** [comment]
跨域请求应该都已经开放了，所有接口都允许跨域请求，不单独针对某一个接口进行限制的。

如果返回503，或许要查看一下是否是你的请求频率过高了，可以查看#63，目前允许每秒请求5次，如果超过频率限制则会返回503错误。
