### ISSUE TITLE
今天api好像使用不了了

### ISSUE THREAD

**Issue by rain7** [BlankerL/DXY-2019-nCoV-Crawler#105]
api今天调用不了，昨天还能用

**Comment by xcy96** [comment]
嗯，我这里也是

**Comment by SoCMo** [comment]
同

**Comment by BlankerL** [comment]
感谢反馈，目前问题已经解决了。

**Comment by rain7** [comment]
好像还没修复，还不能用

**Comment by rain7** [comment]
调用不了 返回错误500 Internal Server Error @BlankerL

**Comment by BlankerL** [comment]
我现在检查一下，如果又出现这种情况了，估计又是有人用无限循环的函数持续请求服务器占满线程了。

**Comment by rain7** [comment]
好的 谢谢

> 我现在检查一下，如果又出现这种情况了，估计又是有人用无限循环的函数持续请求服务器占满线程了。

**Comment by BlankerL** [comment]
目前已经重新恢复，我正在检查之前的logfile，可以先开始使用了

**Comment by rain7** [comment]
> 目前已经重新恢复，我正在检查之前的logfile，可以先开始使用了

嗯，可以用了

**Comment by BlankerL** [comment]
大约1个月之前我重写了整个后端，目前所有请求都是异步加载的，已经稳定运行一个月了。目前问题应该已经解决了，如果之后又发生类似的情况我会及时跟进。感谢反馈！

**Comment by ka1i** [comment]
你好，Api今天 504 Gateway Time-out 了。

**Comment by BlankerL** [comment]
> 你好，Api今天 504 Gateway Time-out 了。

由于今天受到过多请求服务器超过负载又宕机了...很久没有这种情况了，目前已经恢复，正在检查logfile。
