### ISSUE TITLE
api目前好像还是不能用

### ISSUE THREAD

**Issue by rain7** [BlankerL/DXY-2019-nCoV-Crawler#106]
作者你好，目前好像还是不能用

**Comment by rain7** [comment]
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application.</p>

**Comment by BlankerL** [comment]
Duplicate of #105

**Comment by BlankerL** [comment]
我重新打开了#105，统一到那边讨论吧
