### ISSUE TITLE
不要爬这些数据捣乱了，现在不是你们炫技的时候，武汉加油、中国加油！！

### ISSUE THREAD

**Issue by ncc0706** [BlankerL/DXY-2019-nCoV-Crawler#11]

**Comment by BlankerL** [comment]
好的，感谢提醒。不知道这个项目给谁添乱了呢？

是不是[像您一样](https://www.gitmemory.com/ncc0706)只用GitHub更新环境部署类博客、star/fork项目、不看源码就发issue要求解密您忘记密码的加密文件（以至于4个月之后都没有人回复）才是GitHub的正确用法呢？😊
