### ISSUE TITLE
新西兰确诊人数错误

### ISSUE THREAD

**Issue by baihuirong** [BlankerL/DXY-2019-nCoV-Crawler#110]
非常抱歉打扰，在csv的area文件里面，治愈人数大于确诊人数，请问这个怎么办呢？
![image](https://user-images.githubusercontent.com/30078951/82438311-69a9dd80-9acb-11ea-81f6-b717ca35d82f.png)
数据急用，非常非常抱歉

**Comment by baihuirong** [comment]
非常感谢博主求解决 #109

**Comment by BlankerL** [comment]
你好，目前丁香园也是这样的数据。
![DXY](https://user-images.githubusercontent.com/24969376/82631514-2fa21e00-9c28-11ea-9bd9-8ddfccb04b5e.png)

JHU显示的数据是确诊1504人，死亡21人。
![JHU](https://user-images.githubusercontent.com/24969376/82631560-519ba080-9c28-11ea-8ec9-b4931fa81eea.png)

或许是丁香园的数据存在问题。

**Comment by baihuirong** [comment]
一百分感谢大佬🙏。因为我是对海外疫情数据做数据处理。我现在在找丁香园数据的反馈渠道，微信公众号和app都找了，反馈后无回应。请问您这边是否有丁香园数据的上报渠道呢？再次感谢🙏




| |
白惠熔
邮箱：baihuirong111@126.com
|

签名由 网易邮箱大师 定制

在2020年05月22日 12:33，Isaac Lin 写道：

你好，目前丁香园也是这样的数据，具体情况我也不清楚。

JHU显示的数据是确诊1504人，死亡21人。

**Comment by BlankerL** [comment]
> 一百分感谢大佬🙏。因为我是对海外疫情数据做数据处理。我现在在找丁香园数据的反馈渠道，微信公众号和app都找了，反馈后无回应。请问您这边是否有丁香园数据的上报渠道呢？再次感谢🙏 

很抱歉，我也没有渠道能够与丁香园联系，这只是一个采集丁香园数据的项目😭

**Comment by baihuirong** [comment]
再次万分感谢！！！



在 2020-05-24 17:17:09，"Isaac Lin" <notifications@github.com> 写道：

一百分感谢大佬🙏。因为我是对海外疫情数据做数据处理。我现在在找丁香园数据的反馈渠道，微信公众号和app都找了，反馈后无回应。请问您这边是否有丁香园数据的上报渠道呢？再次感谢🙏

很抱歉，我也没有渠道能够与丁香园联系，这只是一个采集丁香园数据的项目😭
