### ISSUE TITLE
新闻接口失效

### ISSUE THREAD

**Issue by Clarkkkk** [BlankerL/DXY-2019-nCoV-Crawler#112]
新闻接口似乎停止更新了，北京最新的新闻只到3月，跨域请求也被拦截了。

**Comment by BlankerL** [comment]
您好，我确认了[新闻接口](https://lab.isaaclin.cn/nCoV/api/news)，目前应该是正常的，另外，跨域请求也是正常的（#5）。

针对单个省份/城市的数据，丁香园在3月23日之后已经不再维护`provinceName`和`provinceId`字段，因此已经查询不到更新的记录，我已经在API中取消这个字段的传入，感谢反馈。
