### ISSUE TITLE
API接口请求异常

### ISSUE THREAD

**Issue by Mazetsz** [BlankerL/DXY-2019-nCoV-Crawler#113]
API接口请求异常，提交请求后，并无数据返回。
通过网页提交请求，网页打不开，应该是api接口有点异常。
异常情况从昨天至今。

**Comment by BlankerL** [comment]
感谢反馈，13:30左右已经恢复了。

**Comment by Mazetsz** [comment]
我才是要谢谢您呢
请问一下，地区新闻是不再维护了吗？
因为看见日期都是挺久的了

「Isaac Lin <notifications@github.com>」在 2020年6月20日 週六，17:32 寫道：
