### ISSUE TITLE
api接口无法访问

### ISSUE THREAD

**Issue by shaxiu** [BlankerL/DXY-2019-nCoV-Crawler#116]
您好，今天不知道什么原因，无法访问您提供的api接口

**Comment by BlankerL** [comment]
由于今天受到过多请求服务器超过负载又宕机了...很久没有这种情况了，目前已经恢复了，正在检查logfile。

**Comment by shaxiu** [comment]
好的，麻烦您了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Isaac Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上11:13
收件人:&nbsp;"BlankerL/DXY-COVID-19-Crawler"<DXY-COVID-19-Crawler@noreply.github.com&gt;;
抄送:&nbsp;"修"<coderxiu@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BlankerL/DXY-COVID-19-Crawler] api接口无法访问 (#116)





 
由于今天受到过多请求服务器超过负载又宕机了...很久没有这种情况了，目前已经恢复了，正在检查logfile。

**Comment by ka1i** [comment]
好的，麻烦你了，感谢!

**Comment by BlankerL** [comment]
> 由于今天受到过多请求服务器超过负载又宕机了...很久没有这种情况了，目前已经恢复了，正在检查logfile。

已解决，请检查自己的IP是否在[黑名单](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/63#issuecomment-586629489)中。
