### ISSUE TITLE
api接口无法访问，504 Gateway Time-out

### ISSUE THREAD

**Issue by BoomingBones** [BlankerL/DXY-2019-nCoV-Crawler#118]
您好，爬虫的api接口无法访问，报错信息与上次一样，是服务器又超载宕机了吗？

**Comment by BlankerL** [comment]
是的，很抱歉今天才看到消息，目前已经处理，详见[此处](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/63#issuecomment-586629489)。
