### ISSUE TITLE
新闻接口不更新数据

### ISSUE THREAD

**Issue by Sikewb** [BlankerL/DXY-2019-nCoV-Crawler#13]
如题，最新一条是9：45吉林省的新闻

**Comment by BlankerL** [comment]
数据应该是正常的，由于爬虫插入条目不会按照时间排序，后端返回数据的时候也不会时间重新排序，因此需要前端重新对时间进行排序。

下图为数据库返回的数据
![image](https://user-images.githubusercontent.com/24969376/73241587-67024000-41dd-11ea-95d5-e5314270589b.png)

下图为丁香园实时播报数据
![image](https://user-images.githubusercontent.com/24969376/73241623-800af100-41dd-11ea-8236-aecfea3f6cea.png)

**Comment by BlankerL** [comment]
TODO
1. 在API中添加返回数据条目变量，以约束返回数据条目并且按时间倒序排列。

**Comment by Sikewb** [comment]
非常感谢，虽然之前是经过排序后最新是9：45那一条，不过刚刚恢复了，可以获取到最新的一条，非常感谢！

**Comment by BlankerL** [comment]
> 非常感谢，虽然之前是经过排序后最新是9：45那一条，不过刚刚恢复了，可以获取到最新的一条，非常感谢！

好的，感谢反馈。为保证数据连贯，已经在服务器添加守护进程，每分钟监控脚本，确保脚本正常运作。

**Comment by BlankerL** [comment]
> 非常感谢，虽然之前是经过排序后最新是9：45那一条，不过刚刚恢复了，可以获取到最新的一条，非常感谢！

检查了一下，历史数据确实有遗漏，已经补全。

**Comment by BlankerL** [comment]
> TODO
> 
> 1. 在API中添加返回数据条目变量，以约束返回数据条目并且按时间倒序排列。

已完成，新闻均以时间倒序排列返回，默认返回前10条新闻。

接口的具体使用方法可以参考[API文档](http://lab.isaaclin.cn/nCoV/)中 **/nCoV/api/news** 部分。
