### ISSUE TITLE
关于“中国”返回的数据

### ISSUE THREAD

**Issue by taylor12138** [BlankerL/DXY-2019-nCoV-Crawler#131]
你好，能把/nCoV/api/area?latest=1&province=中国的city数据也一起返回吗，中国各省都会返回下属的城市city，但是中国的话没返回city,是显示city:null，但是个人又迫切需要一次性获取全国+各省确诊人数信息，但又不能一次性发起多个请求（/nCoV/api/area?latest=1&province=全部省份），会报跨域

**Comment by BlankerL** [comment]
抱歉，丁香园中的数据返回，“中国”是按国别和其他国家排列的，城市则又是单独的一份数据。

如果希望能拿到省份或者城市的数据，可以通过`/nCoV/api/provinceName`拿到省份信息，然后请求每个省份的数据，或者世界请求`/nCoV/api/area?latest=1`数据，再根据省份进行过滤。
