### ISSUE TITLE
关于历史数据  时间序列获取方式疑问

### ISSUE THREAD

**Issue by haiyoushui** [BlankerL/DXY-2019-nCoV-Crawler#143]
https://github.com/BlankerL/DXY-COVID-19-Data/blob/master/json   看说明里  api不提供时间序列的数据  转到json文件夹中，但是貌似这个打不开了 大佬

**Comment by BlankerL** [comment]
抱歉，后来又迭代了一个版本，在[数据仓库](https://github.com/BlankerL/DXY-COVID-19-Data/)的Readme中提到，数据已经放到[数据仓库的Release](https://github.com/BlankerL/DXY-COVID-19-Data/releases)中了。近期修改这边的Readme。

感谢提醒。
