### ISSUE TITLE
部分数据可视化了一下

### ISSUE THREAD

**Issue by cuihuan** [BlankerL/DXY-2019-nCoV-Crawler#16]
部分数据可视化了下，供大家查询，希望短时间内稳定维持哈！

地址：https://github.com/cuihuan/2020_wuhan
网站：http://cuihuan.net/wuhan/news.html

**Comment by BlankerL** [comment]
谢谢支持，已经将本项目列入README文件的[Demo部分](https://github.com/BlankerL/DXY-2019-nCoV-Crawler#demo)！
