### ISSUE TITLE
对开放接口中省市疫情查询的建议

### ISSUE THREAD

**Issue by fanchw** [BlankerL/DXY-2019-nCoV-Crawler#2]
建议省市查询也可以选择直接查看最新的数据，而非只能查看所有数据。

**Comment by wangjiyang** [comment]
API中的数据似乎没有继续更新了

**Comment by snwyz** [comment]
http://lab.isaaclin.cn/nCoV/api/area 该接口返回数据过于滞后😂

**Comment by JoyseeKing** [comment]
api数据滞后了

**Comment by fanchw** [comment]
数据并未滞后，除了全国统计数据，其它数据是按照时间顺序全部查出，最新数据在最后面。

**Comment by BlankerL** [comment]
省份查询在/api/province中可以调用，城市数据在/api/area可以调用，所有返回的数据都是历史数据序列，所以最新的数据都在最下方。由于服务器流量过大，我今天会修改API只返回最新数据。

**Comment by BlankerL** [comment]
API已经完成更新，具体更新可以查看[文档](http://lab.isaaclin.cn/nCoV)，现在，默认请求只返回最新数据。

如需返回历史数据，可以手动添加请求变量latest=0
