### ISSUE TITLE
支持 JSONP 跨域

### ISSUE THREAD

**Issue by differui** [BlankerL/DXY-2019-nCoV-Crawler#20]
首先感谢作者的辛勤劳动。
我发现现有 API 无法在 HTTPS 网址下调用。
可以支持下 JSONP 吗？方便前端跨域。

**Comment by BlankerL** [comment]
后端的接口均已经开启过CORS跨域请求，应该是可以直接实现跨域访问的。我稍后重新测试一下跨域请求是否正常。

**Comment by BlankerL** [comment]
Duplicate of #5

**Comment by differui** [comment]
em... 的确 但是 API 是挂在 HTTP 协议下， HTTPS 的网站网站还是无法跨域的。

**Comment by BlankerL** [comment]
> em... 的确 但是 API 是挂在 HTTP 协议下， HTTPS 的网站网站还是无法跨域的。

感谢指正，服务器已经升级为TLS协议。请尝试一下现在是否可以实现跨域请求。

**Comment by differui** [comment]
@BlankerL 太棒了！
