### ISSUE TITLE
爬取的山东省数据里，各个城市的疑似人数都是0。

### ISSUE THREAD

**Issue by xzh1983** [BlankerL/DXY-2019-nCoV-Crawler#21]
确诊人数没问题。
疑似人数和死亡人数都是0

![image](https://user-images.githubusercontent.com/28338983/73328575-45648f80-4295-11ea-9cfe-911941514122.png)

**Comment by xzh1983** [comment]
不好意思，看了下丁香园，确实没有统计疑似的。如果能抓取疑似的就好了。

**Comment by BlankerL** [comment]
丁香园没有针对城市公开疑似信息数据（可能是地方卫健委没有披露疑似数据），国家的疑似数据是国家卫健委直接披露的。省市的疑似数量不知道是否有稳定可靠的数据来源？如果有则可以抓取。

**Comment by BlankerL** [comment]
Duplicate of #12

**Comment by xzh1983** [comment]
确实没有找到疑似数据源
