### ISSUE TITLE
可否提供根据城市、时间获取确诊数的接口？

### ISSUE THREAD

**Issue by youngfreeFJS** [BlankerL/DXY-2019-nCoV-Crawler#22]
可否提供根据城市、时间区间，获取确诊数的接口？
用于分析新增速率模型

感谢作者的开源分享！

**Comment by BlankerL** [comment]
目前API可以根据省份，提取省份下的所有数据。
例：http://lab.isaaclin.cn/nCoV/api/area?province=湖北省&latest=0
则可以提取到湖北省疫情信息的时间序列变化情况。

可以将数据提取并且保存在本地之后，通过其他方法完成数据清洗和分析。

**Comment by youngfreeFJS** [comment]
收到，多谢
