### ISSUE TITLE
接口不可用

### ISSUE THREAD

**Issue by XiangtingLee** [BlankerL/DXY-2019-nCoV-Crawler#25]
接口不可用，Connection refused

**Comment by XiangtingLee** [comment]
忘记感谢作者，及时开发了这个接口

**Comment by BlankerL** [comment]
为了方便跨域访问，接口加上了SSL证书，地址已经变更为https://lab.isaaclin.cn/nCoV/

已经在README.md文件中修改了，不过可能过于细节大家没有注意，我把这个问题置顶方便更多人查阅。

**Comment by XiangtingLee** [comment]
好的，非常感谢！

**Comment by jinqimu** [comment]
感谢作者，希望在readme前面注明一下更新了SSL，我还以为我半小时一次也被ban了，😂

**Comment by WiseClock** [comment]
我也以为我半小时一次太频繁了……

**Comment by xmaj2008** [comment]
作者应该是在调试改动，昨天好几次连不上之后发现接口改过了，比如suspect，改成了suspectedCount 后来又删掉了suspect，今天又改成了https。
连不上来主页看下就行了。

**Comment by BlankerL** [comment]
> 作者应该是在调试改动，昨天好几次连不上之后发现接口改过了，比如suspect，改成了suspectedCount 后来又删掉了suspect，今天又改成了https。
> 连不上来主页看下就行了。

是的，因为丁香园在改变变量的命名规则，为了保证数据连贯我也只能改变数据库里的变量名，跟随丁香园变化。不过从这两天的状况来看，基本已经稳定了。

**Comment by BlankerL** [comment]
> 感谢作者，希望在readme前面注明一下更新了SSL，我还以为我半小时一次也被ban了，😂

感谢提醒，已经标注。
