### ISSUE TITLE
/api/area的latest=1选项好像返回了以前的数据?

### ISSUE THREAD

**Issue by GaugeAndGravity** [BlankerL/DXY-2019-nCoV-Crawler#28]
一觉醒来一看还以为一夜治愈千人2333

**Comment by hack-fang** [comment]
> 
> 
> 一觉醒来一看还以为一夜治愈千人2333

参照此 ： https://github.com/BlankerL/DXY-2019-nCoV-Crawler/issues/30

**Comment by BlankerL** [comment]
感谢提醒，已经修复。昨天合并数据库之后重新写了一下数据提取的规则，漏写了一条...现在已经好了。
