### ISSUE TITLE
数据似乎不是最新的？

### ISSUE THREAD

**Issue by JoshuaYF** [BlankerL/DXY-2019-nCoV-Crawler#29]
https://lab.isaaclin.cn/nCoV/api/area?latest=1返回的似乎是以前的数据

**Comment by hack-fang** [comment]
> 
> 
> [https://lab.isaaclin.cn/nCoV/api/area?latest=1返回的似乎是以前的数据](https://lab.isaaclin.cn/nCoV/api/area?latest=1%E8%BF%94%E5%9B%9E%E7%9A%84%E4%BC%BC%E4%B9%8E%E6%98%AF%E4%BB%A5%E5%89%8D%E7%9A%84%E6%95%B0%E6%8D%AE)

参照此 https://github.com/BlankerL/DXY-2019-nCoV-Crawler/issues/30

**Comment by BlankerL** [comment]
感谢提醒，已经修复。昨天合并数据库之后重新写了一下数据提取的规则，漏写了一条...现在已经好了。

**Comment by BlankerL** [comment]
Duplicate of #28
