### ISSUE TITLE
接口返回的数据是旧的,请老大看看

### ISSUE THREAD

**Issue by fqhaier** [BlankerL/DXY-2019-nCoV-Crawler#30]
接口返回的数据是旧的,请老大看看
https://lab.isaaclin.cn/nCoV/api/area?latest=1

**Comment by hack-fang** [comment]
确实有该问题，应该是对返回的数据没有作倒序。返回的是最早的一条数据

暂时先使用此 https://lab.ahusmart.com/  替换 https://lab.isaaclin.cn/  ，接口协议完全一致，然后 等待开发者修复吧。

**Comment by BlankerL** [comment]
感谢提醒，已经修复。昨天合并数据库之后重新写了一下数据提取的规则，漏写了一条...现在已经好了。

**Comment by BlankerL** [comment]
Duplicate of #28
