### ISSUE TITLE
可否在接口中加上area_code字段呀

### ISSUE THREAD

**Issue by JoshuaYF** [BlankerL/DXY-2019-nCoV-Crawler#31]
因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。

**Comment by BlankerL** [comment]
丁香园只对国家和省份进行编码，没有对市/区进行编码。

---

2月12日更新：
目前所有丁香园提供`locationId`的条目均已经补全，省级数据已全部补全，市级数据补全90%以上。

暂未补全的条目有：
- 诸如上海市的“外地来沪人员”，无`locationId`编码；
- 其他省份未确定具体数据来源城市而划分出“未明确”条目，无`locationId`编码；
- 各自治区行政规划比较混乱，如新疆“第七师”、“第八师”、“第九师”，无`locationId`编码。

Updated on February 12: 
So far, `locationId` provided by Ding Xiang Yuan is available for all historical data as well. All the province-level data and 90% of city-level have their `locationId`.

`locationId` still not available for:
- Documents such as "Non-local people seeking for medical treatment" for Shanghai, which do not have `locationId`, 
- Infections those are not determined in which city, labeled as "Not sure", which do not have `locationId`, and
- Non-city names such as `Seventh Division`, `Eighth Division` in Xinjiang, which do not have `locationId`.

**Comment by hack-fang** [comment]
> 
> 
> 因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。

你可能需要的是这个。。。  https://github.com/hack-fang/nCov/blob/master/province_cities.json

**Comment by BlankerL** [comment]
> > 因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。
> 
> 你可能需要的是这个。。。 https://github.com/hack-fang/nCov/blob/master/province_cities.json

我没有自己使用这个数据，有“徐汇”/“徐汇区”频繁交替出现的现象吗？

丁香园录入数据的人时常发生变化（丁香园数据中`operator`字段应该指是录入数据的人的ID），所以可能有这种现象发生。

如果是在某个时间点发生改变，就用你提供的这份`json`文件即可；如果是交替出现，我可以在数据录入数据库的时候做一下统一。

**Comment by hack-fang** [comment]
> 
> 
> > > 因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。
> > 
> > 
> > 你可能需要的是这个。。。 https://github.com/hack-fang/nCov/blob/master/province_cities.json
> 
> 我没有自己使用这个数据，有“徐汇”/“徐汇区”频繁交替出现的现象吗？
> 
> 丁香园录入数据的人时常发生变化（丁香园数据中`operator`字段应该指是录入数据的人的ID），所以可能有这种现象发生。
> 
> 如果是在某个时间点发生改变，就用你提供的这份`json`文件即可；如果是交替出现，我可以在数据录入数据库的时候做一下统一。

没有交替出现，问题是丁香园对城市的命名不太统一，有的是xx市，有的是xx 。 这个json文件是我根据丁香园的数据手动整理出来的。。。

**Comment by JoshuaYF** [comment]
> > 因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。
> 
> 你可能需要的是这个。。。 https://github.com/hack-fang/nCov/blob/master/province_cities.json

感谢！

**Comment by JoshuaYF** [comment]
> > > 因为之前接口返回的是类似于徐汇、长宁、浦东...现在变成了徐汇区、长宁区、浦东新区。
> > 
> > 
> > 你可能需要的是这个。。。 https://github.com/hack-fang/nCov/blob/master/province_cities.json
> 
> 我没有自己使用这个数据，有“徐汇”/“徐汇区”频繁交替出现的现象吗？
> 
> 丁香园录入数据的人时常发生变化（丁香园数据中`operator`字段应该指是录入数据的人的ID），所以可能有这种现象发生。
> 
> 如果是在某个时间点发生改变，就用你提供的这份`json`文件即可；如果是交替出现，我可以在数据录入数据库的时候做一下统一。

也不算交替出现，之前上海和北京的都是XX，刚才突然变成了XX区

**Comment by BlankerL** [comment]
😢这方面丁香园确实任性…稍微一变动我们就要跟着改。我尝试把历史数据和未来提取的数据都做一下转换吧。

**Comment by haoyuns** [comment]
另外有个问题，不是丁香园的锅，是各省发布数据的问题：有些地级市下辖的县级市会独立发布数据，需要统一合并，新疆那里的兵团们就更不用说了~

**Comment by BlankerL** [comment]
> 另外有个问题，不是丁香园的锅，是各省发布数据的问题：有些地级市下辖的县级市会独立发布数据，需要统一合并，新疆那里的兵团们就更不用说了~

抱歉，请问有具体的例子吗？我没有对数据进行进一步挖掘，并不是很理解这是什么意思。

**Comment by haoyuns** [comment]
> > 另外有个问题，不是丁香园的锅，是各省发布数据的问题：有些地级市下辖的县级市会独立发布数据，需要统一合并，新疆那里的兵团们就更不用说了~
> 
> 抱歉，请问有具体的例子吗？我没有对数据进行进一步挖掘，并不是很理解这是什么意思。

例如公主岭的数据应该归属于四平市，兵团第四师的数据应该归属于伊宁市，如果按标准地名、或地级市来看的话，卫健委数据里很多没有合并

**Comment by BlankerL** [comment]
> > > 另外有个问题，不是丁香园的锅，是各省发布数据的问题：有些地级市下辖的县级市会独立发布数据，需要统一合并，新疆那里的兵团们就更不用说了~
> > 
> > 
> > 抱歉，请问有具体的例子吗？我没有对数据进行进一步挖掘，并不是很理解这是什么意思。
> 
> 例如公主岭的数据应该归属于四平市，兵团第四师的数据应该归属于伊宁市，如果按标准地名、或地级市来看的话，卫健委数据里很多没有合并

抱歉，我更希望尊重原始数据，如果有后续数据合并的需求，需要自己根据需求来完成。但是您说的这个问题我会在README文件里面告诉使用者。

**Comment by haoyuns** [comment]
>



> > > > 另外有个问题，不是丁香园的锅，是各省发布数据的问题：有些地级市下辖的县级市会独立发布数据，需要统一合并，新疆那里的兵团们就更不用说了~
> > > 
> > > 
> > > 抱歉，请问有具体的例子吗？我没有对数据进行进一步挖掘，并不是很理解这是什么意思。
> > 
> > 
> > 例如公主岭的数据应该归属于四平市，兵团第四师的数据应该归属于伊宁市，如果按标准地名、或地级市来看的话，卫健委数据里很多没有合并
> 
> 抱歉，我更希望尊重原始数据，如果有后续数据合并的需求，需要自己根据需求来完成。但是您说的这个问题我会在README文件里面告诉使用者。

嗯嗯，当然，因为讨论到area code所以想提醒一下

**Comment by BlankerL** [comment]
目前丁香园已经全面返回`locationId`字段，针对中国地区使用邮编，针对其他国家使用的编码暂不确定。我会回溯所有历史数据并且完成编码，完成后会在此Issue内进行通知。

**Comment by BlankerL** [comment]
目前所有丁香园提供`locationId`的条目均已经补全，省级数据已全部补全，市级数据补全90%以上。

暂未补全的条目有：
- 诸如上海市的“外地来沪人员”，无`locationId`编码；
- 其他省份未确定具体数据来源城市而划分出“未明确”条目，无`locationId`编码；
- 各自治区行政规划比较混乱，如新疆“第七师”、“第八师”、“第九师”，无`locationId`编码。

---

So far, `locationId` provided by Ding Xiang Yuan is available for all historical data as well. All the province-level data and 90% of city-level have their `locationId`.

`locationId` still not available for:
- Documents such as "Non-local people seeking for medical treatment" for Shanghai, which do not have `locationId`, 
- Infections those are not determined in which city, labeled as "Not sure", which do not have `locationId`, and
- Non-city names such as `Seventh Division`, `Eighth Division` in Xinjiang, which do not have `locationId`.
