### ISSUE TITLE
获取谣言的API返回内容存在重复

### ISSUE THREAD

**Issue by cary-rowen** [BlankerL/DXY-2019-nCoV-Crawler#32]
Get请求: https://lab.isaaclin.cn/nCoV/api/rumors?num=10 发现返回的Json中存在多条完全相同的数据。
返回数据如下，其中的第5~7条是重复：
{"results": [{"body": "目前尚无证据证明喝茶可以预防新冠病毒。尽量保持室内空气流通，注意卫生，勤洗手，吃熟食，远离人群就是最好的预防手段了。", "id": 93, "mainSummary": "丁香医生团队辟谣：补水挺好，预防病毒没用", "sourceUrl": "", "title": "喝茶可以预防新冠病毒？"}, {"body": "在国家卫健委印发的《新型冠状病毒感染的肺炎诊疗方案（试行第四版）》中显示，新型冠状病毒经呼吸道飞沫传播是主要的传播途径，亦可通过接触传播。而眼神对视不属于前述任何一种。\n另外，造谣网民已被依法处罚。", "id": 92, "mainSummary": "丁香医生团队辟谣：系编造，造谣网民已被依法处罚。", "sourceUrl": "", "title": "新冠病毒通过眼神对视传播？"}, {"body": "太阳的照射温度达不到56℃，且日照紫外线也达不到紫外线消毒灯的强度，不论从哪一个角度都不能达到杀灭病毒的要求。若要外出晒太阳，仍需戴好口罩，做好必要防护。", "id": 91, "mainSummary": "丁香医生团队辟谣：太阳的照射温度达不到 56℃，且日照紫外线也达不到紫外线消毒灯的强度", "sourceUrl": "", "title": "晒太阳可以杀灭新型冠状病毒？"}, {"body": "根据SARS病毒的特点，推测新型冠状病毒可在金属、塑料上存活2～3天，但存活不代表可达到传染条件。\n手机、电梯按键存在的细菌和病毒数量种类众多，不管是否沾染上带有冠状病毒的飞沫，接触后都需好好洗手。不要用脏手碰口鼻、揉眼睛，更不要一边吃东西一边玩手机。\n无症状密切接触史者和轻微症状居家隔离者的手机，需好好消毒，不要触碰。", "id": 90, "mainSummary": "丁香医生团队：接触手机、电梯按键后，需要及时洗手", "sourceUrl": "", "title": "病毒会存在手机和电梯按键上？"}, {"body": "针对此次新型病毒感染，WHO尚未发表中国为「疫区」的声明。很多人在讨论的PHEIC翻译过来是「国际公共卫生紧急事件」，是世卫组织发出的警示信息。根据《国际卫生条例（2005）》规定，PHEIC只是给各国的建议，不是强制措施。", "id": 89, "mainSummary": "丁香医生团队辟谣：根本没有「疫区国」的概念", "sourceUrl": "", "title": "中国被列入疫区国？"}, {"body": "针对此次新型病毒感染，WHO尚未发表中国为「疫区」的声明。很多人在讨论的PHEIC翻译过来是「国际公共卫生紧急事件」，是世卫组织发出的警示信息。根据《国际卫生条例（2005）》规定，PHEIC只是给各国的建议，不是强制措施。", "id": 89, "mainSummary": "丁香医生团队辟谣：根本没有「疫区国」的概念", "sourceUrl": "", "title": "中国被列入「疫区国」？"}, {"body": "针对此次新型病毒感染，WHO尚未发表中国为「疫区」的声明。很多人在讨论的PHEIC翻译过来是「国际公共卫生紧急事件」，是世卫组织发出的警示信息。根据《国际卫生条例（2005）》规定，PHEIC只是给各国的建议，不是强制措施。", "id": 89, "mainSummary": "丁香医生团队辟谣：根本没有“疫区国”的概念", "sourceUrl": "", "title": "中国被列入疫区国？"}, {"body": "在国家卫健委印发的《新型冠状病毒感染的肺炎诊疗方案（试行第四版）》中提到「病毒对紫外线和热敏感，56℃30分钟、乙醚、75%乙醇、含氯消毒剂、过氧乙酸和氯仿等脂溶剂均可有效灭活病毒。」紫外线消毒灯要严格按照说明书的要求使用。且人和宠物都要离开正在消毒的房间，以免对皮肤和眼睛造成损伤。", "id": 88, "mainSummary": "国家卫健委：冠状病毒对紫外线敏感", "sourceUrl": "", "title": "紫外线消毒灯能杀灭新冠病毒？"}, {"body": "在国家卫健委印发的《新型冠状病毒感染的肺炎诊疗方案（试行第四版）》中提到“病毒对紫外线和热敏感，56℃30分钟、乙醚、75%乙醇、含氯消毒剂、过氧乙酸和氯仿等脂溶剂均可有效灭活病毒。”紫外线消毒灯要严格按照说明书的要求使用。且人和宠物都要离开正在消毒的房间，以免对皮肤和眼睛造成损伤。", "id": 88, "mainSummary": "国家卫健委：冠状病毒对紫外线敏感", "sourceUrl": "", "title": "紫外线消毒灯能杀灭新冠病毒？"}, {"body": "国家邮政局市场监管司副司长侯延波表示：“我们要求邮政和快递企业严格落实对邮件、快件、运输车辆、生产作业场所的消毒、通风等措施，严格落实安全查验的制度，严禁收寄野生动物。因此大家不用担心，正常的快件不用拒收，收完快件请及时洗手。”", "id": 87, "mainSummary": "丁香医生团队辟谣：病毒通过快件传播的风险极低，收完快件请及时洗手", "sourceUrl": "", "title": "武汉来的快递要拒收？"}], "success": true}

**Comment by BlankerL** [comment]
已修复，和 #24 情况类似。
