### ISSUE TITLE
接口返回502 bad gateway

### ISSUE THREAD

**Issue by Sikewb** [BlankerL/DXY-2019-nCoV-Crawler#33]
'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\n'

**Comment by Soontao** [comment]
same issue

**Comment by wanghao15536870732** [comment]
![image](https://user-images.githubusercontent.com/32426394/73585313-0aec3400-44db-11ea-88ca-125a4ce80730.png)

**Comment by Dobby233Liu** [comment]
<img src="https://user-images.githubusercontent.com/28653235/73585811-fa8a8800-44df-11ea-9e15-7e37aa7d792d.png" alt="cf worker 502" title="cf worker 502">

**Comment by descarm** [comment]
same issue

**Comment by JoshuaYF** [comment]
same issue

**Comment by Soontao** [comment]
Hello @BlankerL 

Maybe the application server has been  down, could you help to check about that ?

Thank you.

**Comment by xzh1983** [comment]
另外，api的帮助界面也打不开了。

**Comment by JoshuaYF** [comment]
#30 提到：
暂时先使用此 https://lab.ahusmart.com/ 替换 https://lab.isaaclin.cn/ ，接口协议完全一致

**Comment by BlankerL** [comment]
抱歉，服务器访问量过大，已经重启服务器了。

Sorry for the trouble, there are too many connections to the server. I have rebooted the server and it is functioning now.

**Comment by Sikewb** [comment]
> 抱歉，服务器访问量过大，已经重启服务器了。
> 
> Sorry for the trouble, there are too many connections to the server. I have rebooted the server and it is functioning now.

谢谢！

**Comment by BlankerL** [comment]
已经添加uWSGI守护进程[Supervisor](http://supervisord.org/)，测试强制关闭uWSGI后，守护进程会自动重启uWSGI。

Use [Supervisor](http://supervisord.org/) to screen and daemonize uWSGI. After manually killing uWSGI, Supervisor will restart it automatically.
