### ISSUE TITLE
部分关键数据错乱（死亡和治愈人数互换了）！！！

### ISSUE THREAD

**Issue by yansheng836** [BlankerL/DXY-2019-nCoV-Crawler#35]
如广东的数据：
汇总（正确）：
![image](https://user-images.githubusercontent.com/45334066/73605805-cdbc9a80-45dd-11ea-884b-6b2f29021d7b.png)

该省各市数据错乱：
![image](https://user-images.githubusercontent.com/45334066/73605814-dd3be380-45dd-11ea-8789-e70adaed14d6.png)

**Comment by Digital-Chen** [comment]
另，通过API得到的疑似数据大部分为0。请帮忙看看，感谢提供数据。
![Capture](https://user-images.githubusercontent.com/39783879/73605931-a4047300-45df-11ea-81f7-d00453f61647.JPG)

**Comment by BlankerL** [comment]
> 另，通过API得到的疑似数据大部分为0。请帮忙看看，感谢提供数据。
> ![Capture](https://user-images.githubusercontent.com/39783879/73605931-a4047300-45df-11ea-81f7-d00453f61647.JPG)

提问前请先看看已解决的问题里有没有你想问的内容。

**Comment by BlankerL** [comment]
> 另，通过API得到的疑似数据大部分为0。请帮忙看看，感谢提供数据。
> ![Capture](https://user-images.githubusercontent.com/39783879/73605931-a4047300-45df-11ea-81f7-d00453f61647.JPG)

Duplicate of #12

**Comment by BlankerL** [comment]
> 如广东的数据：
> 汇总（正确）：
> ![image](https://user-images.githubusercontent.com/45334066/73605805-cdbc9a80-45dd-11ea-884b-6b2f29021d7b.png)
> 
> 该省各市数据错乱：
> ![image](https://user-images.githubusercontent.com/45334066/73605814-dd3be380-45dd-11ea-8789-e70adaed14d6.png)

请直接使用接口查看数据，Demo不是我开发的，不能保证正常使用接口。

已经确认接口内的数据是正确的。

**Comment by Digital-Chen** [comment]
> > 另，通过API得到的疑似数据大部分为0。请帮忙看看，感谢提供数据。
> > ![Capture](https://user-images.githubusercontent.com/39783879/73605931-a4047300-45df-11ea-81f7-d00453f61647.JPG)
> 
> 提问前请先看看已解决的问题里有没有你想问的内容。

抱歉，谢谢！！！
