### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by yongjun21** [BlankerL/DXY-2019-nCoV-Crawler#40]
我所设立的 scrapper 每过一阵会出现 timeout issues. 不知道是不是丁香园那边根据 IP block 了我的 requests. 你们是否遇到相似的问题？

**Comment by yongjun21** [comment]
更深入的调查发现跟 IP 和 User-Agent 没太大关系。暂时用 retry 的方式来 workaround timeout 的问题。

**Comment by BlankerL** [comment]
应该是访问量太大，服务器短时间内失去响应了。
