### ISSUE TITLE
似乎所有的省份里面的疑似人数都是0

### ISSUE THREAD

**Issue by langyuxiansheng** [BlankerL/DXY-2019-nCoV-Crawler#45]
四川
![image](https://user-images.githubusercontent.com/29669030/73938642-a4c04080-4922-11ea-9be9-341c946db982.png)
湖北
![image](https://user-images.githubusercontent.com/29669030/73938674-b6094d00-4922-11ea-880c-6b8b6d5772a3.png)

**Comment by BlankerL** [comment]
Duplicate of #12
