### ISSUE TITLE
希望开放API接口实现代码

### ISSUE THREAD

**Issue by swordry** [BlankerL/DXY-2019-nCoV-Crawler#46]
文中提到的API： https://lab.isaaclin.cn/nCoV/ ，能否开放具体实现。需要把具体的搬到一个内部网络做展示，非商业用途，谢谢！

**Comment by BlankerL** [comment]
API并没有打算开源。

**我提供API的初衷，是为了减少爬虫和其他需要数据的人对丁香园的请求，同时减少大家对爬虫的部署。** 因为大部分用户部署爬虫其实是希望基于这部分数据进行二次开发，而不是使用爬虫本身。如果将API开源，就必定会有很多人开始部署爬虫+API，则“为丁香园减压”的目的就达不到了。

另外，我不太能理解所谓的“内部网络”是什么意思？
1. 如果你需要在一个无公网访问权限的网络内部署API给其他本地设备使用，那么你需要怎么部署爬虫来获取数据呢？
2. 如果网络内有至少一台设备能够访问公共网络，你就只需要用这台设备做一个很基础的数据转发就可以了。
