### ISSUE TITLE
有脏数据

### ISSUE THREAD

**Issue by Norcy** [BlankerL/DXY-2019-nCoV-Crawler#47]
https://lab.isaaclin.cn/nCoV/api/area?latest=0&province=%E6%B2%B3%E5%8C%97%E7%9C%81

比如石家庄在 2 月 5 日有一条数据的确诊人数是 33，但是其他时间点却是 21

**Comment by BlankerL** [comment]
API相关内容在这个项目的 #34 进行反馈，[BlankerL/DXY-2019-nCoV-Data](https://github.com/BlankerL/DXY-2019-nCoV-Data)仅做数据仓库使用。

**Comment by BlankerL** [comment]
麻烦附上数据和具体的时间，方便在数据库中查询。感谢。

**Comment by Norcy** [comment]
> 麻烦附上数据和具体的时间，方便在数据库中查询。感谢。

这个时间点 1580862282159

**Comment by BlankerL** [comment]
> > 麻烦附上数据和具体的时间，方便在数据库中查询。感谢。
> 
> 这个时间点 1580862282159

感谢，已经对照前后时间点确认数据确实有误，已移除。
