### ISSUE TITLE
请放开接口的跨域请求限制

### ISSUE THREAD

**Issue by gucciwu** [BlankerL/DXY-2019-nCoV-Crawler#5]
麻烦增加cors的配置，放开跨域访问权限

**Comment by BlankerL** [comment]
好的，由于丁香园历史数据和最新数据的变量名不一致，需要先对这部分数据进行维护。其他更新会在今天晚上陆续完成。

**Comment by BlankerL** [comment]
所有API均已开放跨域资源共享，可跨域请求API并实现所需功能。
