### ISSUE TITLE
写了一个记录从1月24日疫情爆发以来的确诊病例数据可视化网页渲染脚本

### ISSUE THREAD

**Issue by Minghou-Lei** [BlankerL/DXY-2019-nCoV-Crawler#51]
项目地址 ：https://github.com/Mistletoer/NCP-historical-data-visualization-2019-nCoV-

感谢BlankerL提供的数据仓库！利用pyecharts实现的新型冠状病毒疫情数据可视化

数据源： https://github.com/BlankerL/DXY-2019-nCoV-Crawler

可视化： https://github.com/pyecharts/pyecharts

**Comment by BlankerL** [comment]
感谢，已经纳入README中。
