### ISSUE TITLE
两个重要通知 | Two Important Notices

### ISSUE THREAD

**Issue by BlankerL** [BlankerL/DXY-2019-nCoV-Crawler#53]
首先，十分感谢大家对这个项目的支持。

1. 如果大家有关注README文档上API Call的数量，会发现近期API调用量急剧增加。目前每秒的API调用次数超过10次，忙时出站流量每小时超过1GB，出站速率1MB/s，几乎已经达到目前服务器的峰值10Mbps。
其中，有部分IP每秒请求超过5次，访问IP并没有跳转到前端地址或请求头，暂时也无法判断是否是恶意爬虫。如果未来仍然会有如此庞大的出站流量，为了保证大多数人能够调用本API，我**不排除添加适当的反爬虫手段的可能性**。
另外，我的服务器部署在阿里云华东2区（上海），如果有同样部署在此区域的朋友，可以直接走**内网互通**获取数据，内网IP为：**172.17.10.166**，目前CPU负载不到30%，通过内网获取数据理论上不会受到速度限制。

2. 为了保证API高可用，我已经至少3次迁移服务器，且所有服务器都是自费购买，大家应该也清楚上行带宽10Mbps的服务器的月均价格...因此，从今天开始，我会在API页面投放部分广告，来覆盖服务器开支。如果方便的话，随手点一下广告，就能保证这个API继续运行下去。

---
Thank you for very much for you support for this project.

1. If you have notice the API Call in README file, you will find the calls have increased dramatically recently. The API is now called 10 times per second, and the outbound traffic is over 1 GB per hour, around 1 MB/s, which is almost reaching the upper bound of my server. 
Among the API calls, some of the IP will call the API over 5 times per second, and those IP do not have a proper front end or request header. If the traffic keeps this busy, in order to make sure most of people will be available to the data, I **might add some anti-crawler strategies to the API**. 
Furthermore, my server is hosted on Alibaba Cloud East China Zone 2 (Shanghai). If you are also hosting your service in this zone, you could **directly connect my server through intranet**, the intranet IP address is **172.17.10.166**. Currently, the CPU load is about 30%, so, theoretically, the speed of intranet traffic will not be limited.

2. In order to ensure the high availability of the API, I have migrated the server at least 3 times, and all the servers are purchased on my own. Therefore, starting today, I will put some advertisement to cover the server expenses. If it is convenient for you, please just click on the advertisement and you can ensure that this API continues to run.

**Comment by hganycall** [comment]
收到，感谢作者。一定会点击广告支持。

发送自 Windows 10 版邮件应用

**Comment by BlankerL** [comment]
感谢支持。

**Comment by more-ka** [comment]
好的, 多谢作者

**Comment by iamzchi** [comment]
感谢作者

**Comment by chisaki-takahashi** [comment]
感谢作者

**Comment by LiuTianyong** [comment]
感谢作者

**Comment by lichaohui314** [comment]
感谢作者

**Comment by owen0o0** [comment]
可以在GitHub托管你的数据库仓库，这样就可以通过url直接访问json数据了，比如https://owen0o0.github.io/DXY-COVID-19-Data/json/DXYOverall.json

**Comment by zhaisc2001** [comment]
十分感谢

**Comment by BlankerL** [comment]
> 可以在GitHub托管你的数据库仓库，这样就可以通过url直接访问json数据了，比如https://owen0o0.github.io/DXY-COVID-19-Data/json/DXYOverall.json

你的这个项目应该就是fork的我的数据仓库，只是增加了一个GitHub Pages而已。

事实上，根本不需要做成GitHub Pages，直接用GitHub Raw Content也可以实现同样的效果（就是在json文件页面点击一下raw按钮，使用那个链接就好），我的数据仓库json的部分就是为了这个目的而提供的。应该大部分有这个需求的人也不会再额外fork然后坐GitHub Pages了，毕竟要经常pull新的更新也不方便，而且这个pull的操作应该是不好设置成定时任务，只能手动pull的（不确定GitHub有没有这方面的API）。

API和数据仓库的目的不一样，API是开放给有实时数据展示需求的人，对数据的更新频率比较敏感；数据仓库是开放给做科研的人，对数据的更新频率不太敏感的那部分人使用的。

GitHub的数据更新频率有限，数据库和API的数据是分钟级更新，而GitHub数据仓库的数据目前是小时级更新。如果我频繁推送更新到GitHub可能有封号风险。

综合这几点考虑，最后还是自己用服务器提供API，否则理论上来说，所有的API都是可以架设在GitHub上，让GitHub来承担流量的。

**Comment by owen0o0** [comment]
> > 可以在GitHub托管你的数据库仓库，这样就可以通过URL直接访问json数据了，可以https://owen0o0.github.io/DXY-COVID-19-Data/json/DXYOverall.json
> 
> 你的这个项目应该就是fork的我的数据仓库，只是增加了一个GitHub Pages而已。
> 
> 实际上，根本不需要重构GitHub Pages，直接用GitHub Raw Content也可以实现同样的效果（就是在json文件页面点击一下raw按钮，使用那个链接就好），我的数据仓库json的部分就是为了这个应该而有的。应该大部分有这个需求的人也不会再额外fork然后坐GitHub Pages了，毕竟要经常pull新的更新也不方便，而且这个pull的操作应该是不好设置成定时任务，只能手动pull的（不确定GitHub有没有这方面的API）。
> 
> API和数据仓库的目的不一样，API是开放给有实时数据展示需求的人，对数据的更新频率比较敏感；数据仓库是开放给做科研的人，对数据的更新频率不太敏感的那部分人使用的。
> 
> GitHub的数据更新频率有限，数据库和API的数据是分钟级更新，而GitHub数据仓库的数据目前是小时级更新。如果我替换推送更新到GitHub可能有封号风险。
> 
> 综合这几点考虑，最后还是自己用服务器提供API，否则理论上来说，所有的API都可以架设在GitHub上，让GitHub来承担流量的。

确实更方便，感谢

**Comment by incognico** [comment]
One could also use gitcdn to fetch the json from the data repo: https://gitcdn.xyz/repo/BlankerL/DXY-COVID-19-Data/master/json/DXYOverall.json This is probably the fastest and easiest way (no github pages involved and proper Content-Type).

**Comment by Dobby233Liu** [comment]
> One could also use gitcdn to fetch the json from the data repo: [https://gitcdn.xyz/repo/BlankerL/DXY-COVID-19-Data/master/json/DXYOverall.json](https://gitcdn.xyz/repo/BlankerL/DXY-COVID-19-Data/master/json/DXYOverall.json) This is probably the fastest and easiest way (no github pages involved and proper Content-Type).

actually, there are lots of CDNs you can use. `raw.githack.com`, `cdn.statically.io`, `cdn.jsdelivr.net` etc. can achieve that, too.

**Comment by BlankerL** [comment]
@incognico @Dobby233Liu Thank you so much for this comment, I do not even know these CDN. I will mention them on the README file for that project. 

But I suppose the data warehouse I stored on GitHub will always be data updated less frequently, so the API might be a better choice for those real-time API users? I have never seen someone push real-time data onto GitHub and make a repository to an API.

**Comment by Dobby233Liu** [comment]
> But I suppose the data warehouse I stored on GitHub is less frequent updated, so the API might be a better choice for those real-time users?

Agree.

> I have never seen someone push real-time data onto GitHub and make a repository to an API.

(Maybe/I think) no one would. It can cause a big load placed on GitHub, and may increase the size of the repo (unpleasant to `git clone` users, unless they only clone data(s) of a single commit/they're shallow cloning [downloading a zip snapshot of] a single commit/downloading a single file from a single commit using raw feature or cdn or something else idk).

**Comment by LinJ-C** [comment]
502 Bad Gateway

**Comment by weixinbao** [comment]
502 Bad Gateway

**Comment by Jokertion** [comment]
502 Bad Gateway

**Comment by chengbg** [comment]
API已打不开，502 Bad Gateway

**Comment by BlankerL** [comment]
@LinJ-C @weixinbao @Jokertion @chengbg 目前API已恢复。

我检查了一下logfile，当前的请求数量已经过于庞大，logfile写入出现OS Error，可能因此出现502，我目前暂时关闭logfile的请求记录，仅保留错误记录，已经解决了这个问题。我会在今明两天寻找解决方案，可能考虑使用部分反爬虫措施或限制单个IP的请求频率。

**Comment by Jokertion** [comment]
感谢作者，已点广告支持

**Comment by BlankerL** [comment]
> > But I suppose the data warehouse I stored on GitHub is less frequent updated, so the API might be a better choice for those real-time users?
> 
> Agree.
> 
> > I have never seen someone push real-time data onto GitHub and make a repository to an API.
> 
> (Maybe/I think) no one would. It can cause a big load placed on GitHub, and may increase the size of the repo (unpleasant to `git clone` users, unless they only clone data(s) of a single commit/they're shallow cloning [downloading a zip snapshot of] a single commit/downloading a single file from a single commit using raw feature or cdn or something else idk).

Thank you so much for the detailed explanation. I have searched a lot and I think there is no widely-discussed GitHub-based API. I will continue use the site to feed the real-time data, and try to deal with the increasing traffic.

**Comment by xpader** [comment]
谢谢楼主，我目前也在使用。
我是每5分钟从API拉取存在缓存，前端从缓存中获取。

**Comment by BlankerL** [comment]
> 谢谢楼主，我目前也在使用。
> 我是每5分钟从API拉取存在缓存，前端从缓存中获取。

感谢，我也希望大部分人能通过这种方式实现，或者至少是通过js来实现异步加载。

但是目前我知道的情况是，有不少项目还是在用户访问可视化项目的时候，通过后端来提取数据并渲染进他们的前端里，其实这对于他们的后端来说也是一个比较严重的开销...之前我在群上知道的一个项目是每秒请求一次更新本地缓存...其实对双方都不太友好😓

**Comment by shirvian** [comment]
十分感谢~

**Comment by Norcy** [comment]
点广告！！谢谢作者

**Comment by jingjtang** [comment]
非常感谢！

**Comment by HJ735100504gitup** [comment]
500 Internal Server error

**Comment by BlankerL** [comment]
> 500 Internal Server error

抱歉，已经解决。

**Comment by HJ735100504gitup** [comment]
thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Isaac Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 中午11:37
收件人:&nbsp;"BlankerL/DXY-COVID-19-Crawler"<DXY-COVID-19-Crawler@noreply.github.com&gt;;
抄送:&nbsp;"none"<2511249504@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BlankerL/DXY-COVID-19-Crawler] 两个重要通知 | Two Important Notices (#53)



 
500 Internal Server error
  
抱歉，已经解决。

**Comment by HJ735100504gitup** [comment]
> > 500 Internal Server error
> 
> 抱歉，已经解决。

十分感谢 经过接口调用area有时会503 Service Temporarily Unavailable提示错误信息

**Comment by BlankerL** [comment]
> > > 500 Internal Server error
> > 
> > 
> > 抱歉，已经解决。
> 
> 十分感谢 经过接口调用area有时会503 Service Temporarily Unavailable提示错误信息

请求频率太高会返回503，可以参考#63，请将请求频率限制在1秒2次以内。

**Comment by HJ735100504gitup** [comment]
> > > > 500 Internal Server error
> > > 
> > > 
> > > 抱歉，已经解决。
> > 
> > 
> > 十分感谢 经过接口调用area有时会503 Service Temporarily Unavailable提示错误信息
> 
> 请求频率太高会返回503，可以参考#63，请将请求频率限制在1秒2次以内。

请求频率不高   一两个小时请求一次这样的

**Comment by BlankerL** [comment]
> > > > > 500 Internal Server error
> > > > 
> > > > 
> > > > 抱歉，已经解决。
> > > 
> > > 
> > > 十分感谢 经过接口调用area有时会503 Service Temporarily Unavailable提示错误信息
> > 
> > 
> > 请求频率太高会返回503，可以参考#63，请将请求频率限制在1秒2次以内。
> 
> 请求频率不高 一两个小时请求一次这样的

那应该不会发生这样的状况的，我刚才测试也是正常的，而且也暂时没有听到其他人回报。今天上午服务器有过1个小时左右的离线，目前已经解决了。

**Comment by Dkngit** [comment]
我是每6小时获取一次你的数据存在库里，前端是从自己的库和后端调用。
快表扬我

**Comment by HJ735100504gitup** [comment]
> > > > > > 500 Internal Server error
> > > > > 
> > > > > 
> > > > > 抱歉，已经解决。
> > > > 
> > > > 
> > > > 十分感谢 经过接口调用area有时会503 Service Temporarily Unavailable提示错误信息
> > > 
> > > 
> > > 请求频率太高会返回503，可以参考#63，请将请求频率限制在1秒2次以内。
> > 
> > 
> > 请求频率不高 一两个小时请求一次这样的
> 
> 那应该不会发生这样的状况的，我刚才测试也是正常的，而且也暂时没有听到其他人回报。今天上午服务器有过1个小时左右的离线，目前已经解决了。

感谢

**Comment by Mrsswen** [comment]
现在好多接口都关闭了，想找到一个好点的接口不容易，又没有本事从bat爬下来数据，作为一个学生仔真是太感谢了

**Comment by yayxs** [comment]
技术贡献，感谢

**Comment by MonianHello** [comment]
感谢贡献

**Comment by HJ735100504gitup** [comment]
https://lab.isaaclin.cn/nCoV/此地址访问不了了啊


------------------ 原始邮件 ------------------
发件人:&nbsp;"Isaac Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 中午11:37
收件人:&nbsp;"BlankerL/DXY-COVID-19-Crawler"<DXY-COVID-19-Crawler@noreply.github.com&gt;;
抄送:&nbsp;"none"<2511249504@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BlankerL/DXY-COVID-19-Crawler] 两个重要通知 | Two Important Notices (#53)



 
500 Internal Server error
  
抱歉，已经解决。

**Comment by BlankerL** [comment]
> [https://lab.isaaclin.cn/nCoV/](https://lab.isaaclin.cn/nCoV/%E6%AD%A4%E5%9C%B0%E5%9D%80%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86%E4%BA%86%E5%95%8A) 此地址访问不了了啊

目前已经恢复，已经在 BlankerL/DXY-COVID-19-Data#47 回复。

**Comment by HJ735100504gitup** [comment]
感谢贡献

**Comment by HJ735100504gitup** [comment]
好像访问不了了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Isaac Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 中午12:43
收件人:&nbsp;"BlankerL/DXY-COVID-19-Crawler"<DXY-COVID-19-Crawler@noreply.github.com&gt;;
抄送:&nbsp;"JacksonXu"<2511249504@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BlankerL/DXY-COVID-19-Crawler] 两个重要通知 | Two Important Notices (#53)





  
https://lab.isaaclin.cn/nCoV/此地址访问不了了啊
  
目前已经恢复，已经在 BlankerL/DXY-COVID-19-Data#47 回复。

**Comment by Jokertion** [comment]
最后一次正常访问是北京时间3月16日13:58

**Comment by BlankerL** [comment]
@HJ735100504gitup @Jokertion 麻烦参考#82
