### ISSUE TITLE
引用API里的数据做了R0的模型

### ISSUE THREAD

**Issue by yijunwang0805** [BlankerL/DXY-2019-nCoV-Crawler#55]
你好，

我引用你的API里的数据建了[模型及预测](https://github.com/yijunwang0805/YijunWang)。

已经在github中模型文件readme申明了（并且未来会在主页readme更新和图片上做标注）

致谢你的付出，点击广告支持

王一君

**Comment by BlankerL** [comment]
万分感谢！我已经在README中添加此项目。
