### ISSUE TITLE
国内历史数据和其他国家的实时数据历史数据能否处理一下？

### ISSUE THREAD

**Issue by XIRALIP** [BlankerL/DXY-2019-nCoV-Crawler#56]

**Comment by BlankerL** [comment]
麻烦具体说明一下，目前数据有什么问题？

**Comment by XIRALIP** [comment]
我想查全国各省各市相对昨天的新增数据，这个需要有历史数据，例如：【全国，省，市】当前/确诊/治愈/死亡数据，新增/确诊/治愈/死亡数据。
同样我想查询当前别的国家疫情情况，比如 【日本，新加坡，美国】当前/确诊/治愈/死亡数据，新增/确诊/治愈/死亡数据。

**Comment by BlankerL** [comment]
> 我想查全国各省各市相对昨天的新增数据，这个需要有历史数据，例如：【全国，省，市】当前/确诊/治愈/死亡数据，新增/确诊/治愈/死亡数据。
> 同样我想查询当前别的国家疫情情况，比如 【日本，新加坡，美国】当前/确诊/治愈/死亡数据，新增/确诊/治愈/死亡数据。

所有中国精确到市级、其他国家精确到国家级的实时数据和历史数据在API和数据仓库均有提供，提问前麻烦先阅读[README文件](https://github.com/BlankerL/DXY-COVID-19-Crawler/blob/master/README.md)及[API文档](https://lab.isaaclin.cn/nCoV/zh)。

新增数据并没有直接返回，需要自己求差计算，我列出的Demo和Research项目有其他人已经完成的开源数据处理代码，可以先阅读和参考他们的数据处理方法。
