### ISSUE TITLE
API接口无响应

### ISSUE THREAD

**Issue by hack-fang** [BlankerL/DXY-2019-nCoV-Crawler#6]
http://lab.isaaclin.cn/nCoV/ 该网址也无法访问

**Comment by liguobao** [comment]
好像是的

**Comment by wangjiyang** [comment]
同样无响应

**Comment by yuanzhoulvpi2017** [comment]
无响应，我这也是

**Comment by liguobao** [comment]
没找到API代码，我倒是可以部署一个到国内。

**Comment by yuanzhoulvpi2017** [comment]
我自己直接爬丁香园吧，也很简单，但是没有历史数据了

发自我的iPhone

在 2020年1月27日，12:42，李国宝 <notifications@github.com> 写道：

﻿

没找到API代码，我倒是可以部署一个到国内。

**Comment by liguobao** [comment]
爬取代码没什么，之前部署的API 代码想要。

**Comment by yuanzhoulvpi2017** [comment]
希望你们加油，我这用R爬动态网站太难了

发自我的iPhone

在 2020年1月27日，13:32，李国宝 <notifications@github.com> 写道：

﻿

爬取代码没什么，之前部署的API 代码想要。

**Comment by gucciwu** [comment]
今早发现API用不了了，forker代码写了一个，现在放在公有云在跑，今早之前的数据正在想办法恢复https://github.com/gucciwu/pcc-2019-nCoV

**Comment by BlankerL** [comment]
API已经恢复，之前没有使用负载均衡，因为流量过大和并发量太大，所以服务掉线了。暂时已经恢复，今天会加上负载均衡。
