### ISSUE TITLE
是否增加现存确诊、现存疑似字段

### ISSUE THREAD

**Issue by wjchenge** [BlankerL/DXY-2019-nCoV-Crawler#60]
目前丁香园数据新增了这两个字段，是否接口也响应增加，谢谢

**Comment by chisaki-takahashi** [comment]
目前overall接口中已经增加现存确诊和现存疑似，请求省份数据接口area目前未增加，可以使用接口返回的确诊-死亡-治愈得出省份的现存确诊

**Comment by wjchenge** [comment]
好的，谢谢作者

**Comment by BlankerL** [comment]
> 目前overall接口中已经增加现存确诊和现存疑似，请求省份数据接口area目前未增加，可以使用接口返回的确诊-死亡-治愈得出省份的现存确诊

所有响应数据的数据格式都保持和丁香园一致，如果丁香园没有在省份数据接口响应这个字段，则API也不会额外增加这个响应。因为能够通过后端完成的计算工作，理论上前端都可以完成，而如果每一次响应后端都要计算这部分的数值，则会严重影响响应速度。

**Comment by chisaki-takahashi** [comment]
> > 目前overall接口中已经增加现存确诊和现存疑似，请求省份数据接口area目前未增加，可以使用接口返回的确诊-死亡-治愈得出省份的现存确诊
> 
> 所有响应数据的数据格式都保持和丁香园一致，如果丁香园没有在省份数据接口响应这个字段，则API也不会额外增加这个响应。因为能够通过后端完成的计算工作，理论上前端都可以完成，而如果每一次响应后端都要计算这部分的数值，则会严重影响响应速度。

丁香园已经在省份数据中列出了现存确诊，我的本意也是在从API拉取之后自行计算这个数据。

**Comment by BlankerL** [comment]
> > > 目前overall接口中已经增加现存确诊和现存疑似，请求省份数据接口area目前未增加，可以使用接口返回的确诊-死亡-治愈得出省份的现存确诊
> > 
> > 
> > 所有响应数据的数据格式都保持和丁香园一致，如果丁香园没有在省份数据接口响应这个字段，则API也不会额外增加这个响应。因为能够通过后端完成的计算工作，理论上前端都可以完成，而如果每一次响应后端都要计算这部分的数值，则会严重影响响应速度。
> 
> 丁香园已经在省份数据中列出了现存确诊，我的本意也是在从API拉取之后自行计算这个数据。

是的，我查看了api返回数据，目前应该是有精确到市级的`currentConfirmedCount`字段返回的。
