### ISSUE TITLE
API返回英文字段 | API Returns English Fields

### ISSUE THREAD

**Issue by BlankerL** [BlankerL/DXY-2019-nCoV-Crawler#61]
感谢大家对项目的支持。

目前API`/nCoV/api/area`已经能够返回英文字段，包括大洲名`continentEnglishName`、国家名`countryEnglishName`、省份名`provinceEnglishName`、城市名`cityEnglishName`。

具体内容已经在[API文档](https://lab.isaaclin.cn/nCoV/zh)内注明。

所有英文城市名均手动摘录自维基百科对应城市页面，为城市名全称，确保能够被大多数人接受和理解。

所有历史数据也已经处理完成。

另外，由于返回字段的增加，每次请求返回数据量势必增加，因此网站每秒能够响应的请求数量又将减少，请大家不要再频繁请求API。

---

Thank you for your support.

Currently, API is able to return English fields, the attribute names are the name of the continent `continentEnglishName`, the name of the country `countryEnglishName`, the name of the province `provinceEnglishName` and the name of the city`cityEnglishName`. 

The detailed information can be found in [API documentation](https://lab.isaaclin.cn/nCoV/en).

All the English names of cities are manually collected from Wikipedia and are full names of the cities, which I suppose will help most of the people understand them.

Historical data also contain the English version of city names now. 

Furthermore, due to the increase in the returned fields, the amount of data responded per request will inevitably increase, so the number of requests that the website can respond to per second will decrease again. Please do not call the API frequently.

**Comment by BlankerL** [comment]
历史数据已经处理完毕，所有中国地区数据均包含英文城市名称。稍后将处理境外数据。

---

Historical data has been processed, and all China data includes English city names. I will focus on countries other than China later on.

**Comment by Dobby233Liu** [comment]
I suppose I can fix your Engrish:
> Currently, the `/nCoV/api/area` API is able to return fields translated to English, including name of the continent as `continentEnglishName`, name of the country as `countryEnglishName`, name of the province as `provinceEnglishName` and name of the city as `cityEnglishName`.
> ...
> Now historical data contains translated fields, too.

The title is changed accordingly:

> API returns translated fields

**Comment by BlankerL** [comment]
> I suppose I can fix your Engrish:
> 
> > Currently, the `/nCoV/api/area` API is able to return fields translated to English, including name of the continent as `continentEnglishName`, name of the country as `countryEnglishName`, name of the province as `provinceEnglishName` and name of the city as `cityEnglishName`.
> > ...
> > Now historical data contains translated fields, too.
> 
> The title is changed accordingly:
> 
> > API returns translated fields

Thank you for your advice, I switched to your version for seconds and switch back because I think all the English version of the names of cities is published on Wikipedia. I do not do the translating job, and the translation might be globally-accepted.

**Comment by chffby** [comment]
请问新闻接口是不是不稳定呢，两天没能用了

**Comment by BlankerL** [comment]
> 请问新闻接口是不是不稳定呢，两天没能用了

已经恢复。
