### ISSUE TITLE
天津市数据问题

### ISSUE THREAD

**Issue by Avens666** [BlankerL/DXY-2019-nCoV-Crawler#64]
1月30日，天津的数据， 有宁河区，还有个宁河，这是重复的，这个宁河的数据应该去掉

**Comment by BlankerL** [comment]
麻烦具体到时间点...

另外，异常数据反馈有专门的Issue进行回报，可以参考#34。我已经做了Reference，这条数据的问题就在这边讨论吧。

**Comment by BlankerL** [comment]
已在[#34](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/34#issuecomment-586999358)处理。
