### ISSUE TITLE
谣言部分去掉了ID参数？

### ISSUE THREAD

**Issue by fdsuf** [BlankerL/DXY-2019-nCoV-Crawler#66]
这个项目还在更新吗？
测试时谣言返回信息没有ID编号，建议加上，虽然可以本地加

**Comment by BlankerL** [comment]
项目更新情况可以查看[此处](https://github.com/BlankerL/DXY-COVID-19-Crawler/commits/master)。
API可用情况可以查看[此处](https://lab.isaaclin.cn/nCoV/)。

谣言部分一直没有返回ID，已应要求添加`_id`。

**Comment by BlankerL** [comment]
丁香园替换了谣言文件，原先的静态文件已经不再更新，因此数据库内谣言部分没有持续更新，历史数据已经补全。

同时，已经在最新的一个版本[`14d1086`](https://github.com/BlankerL/DXY-COVID-19-Crawler/commit/14d1086886ca07b13db61f1b58fc9c40f135d0da)中修改为从HTML解析谣言，未来会自动更新。
