### ISSUE TITLE
2月15日之后没有country和continents信息的问题

### ISSUE THREAD

**Issue by Jokertion** [BlankerL/DXY-2019-nCoV-Crawler#68]
请问，2月15日之后没有country和continents信息，是字段名称有修改吗？

**Comment by Jokertion** [comment]
知道了，原来是之前的字段名称有更改
更改内容如下：
continents--->continentName
country--->countryName

**Comment by BlankerL** [comment]
抱歉，因为添加英文字段，所以对中文字段名称也进行了修改。

**Comment by Jokertion** [comment]
> 抱歉，因为添加英文字段，所以对中文字段名称也进行了修改。

明白了，感谢回复。
ps：现在广告位没有了啊？

**Comment by BlankerL** [comment]
> > 抱歉，因为添加英文字段，所以对中文字段名称也进行了修改。
> 
> 明白了，感谢回复。
> ps：现在广告位没有了啊？

Google Adsense 在进行审核，我也不清楚什么时候能结束。不过在反爬虫之后响应速度已经提高了不少，服务器暂时也没有继续升级的必要了，现在这个开支还在我预期范围内😄

感谢支持。
