### ISSUE TITLE
项目的API代码在哪来的？我这边想部署一个到国内。

### ISSUE THREAD

**Issue by liguobao** [BlankerL/DXY-2019-nCoV-Crawler#7]

**Comment by gucciwu** [comment]
今早发现API用不了了，forker代码写了一个，现在放在公有云在跑，今早之前的数据正在想办法恢复https://github.com/gucciwu/pcc-2019-nCoV

**Comment by BlankerL** [comment]
抱歉，API源码暂时没有开放。
