### ISSUE TITLE
治愈率  和 死亡率 是怎么计算的？

### ISSUE THREAD

**Issue by crazyYG** [BlankerL/DXY-2019-nCoV-Crawler#70]

**Comment by BlankerL** [comment]
所有的数据都是从丁香园获取，并没有额外的人为处理，如果对计算口径有疑问可以参考丁香园的网站。

另外，返回数据中并没有治愈率和死亡率数据，你确定是使用本项目提供的API获取到的这份数据吗？

**Comment by crazyYG** [comment]
返回的数据没有并没有治愈率和死亡率数据，我只是想知道 怎么计算
