### ISSUE TITLE
英文名部分缺失和错误

### ISSUE THREAD

**Issue by Tilendlesa** [BlankerL/DXY-2019-nCoV-Crawler#71]
英国United Kingdom写作United Kiongdom。
英文名缺失：
阿联酋 ->United Arab Emirates
克罗地亚 ->Croatia
北马其顿 ->North Macedonia
安道尔 -> Andorra
多米尼加 ->Dominican Republic

**Comment by BlankerL** [comment]
感谢，已经处理。所有历史数据也已经修正。

**Comment by BlankerL** [comment]
非常感谢！缺失的国家也已经补充。
