### ISSUE TITLE
疫情新闻与谣言如何分页获取？

### ISSUE THREAD

**Issue by YangRT** [BlankerL/DXY-2019-nCoV-Crawler#72]
你好，目前疫情新闻与谣言API只能返回指定条数或所有条数，请问如何分页获取？

**Comment by BlankerL** [comment]
你好，抱歉暂时没有分页功能。如果需要在前端实现翻页，可以考虑提取JSON数据、储存在你的后端中并定时更新。

**Comment by YangRT** [comment]
> 你好，抱歉暂时没有分页功能。如果需要在前端实现翻页，可以考虑提取JSON数据、储存在你的后端中并定时更新。

好的，谢谢

**Comment by BlankerL** [comment]
你好，已经增加分页功能。

可以通过/nCoV/api/news?page=2&num=10，指定返回数据的页码以及每页的数目，具体内容可以参考[API文档](https://lab.isaaclin.cn/nCoV/zh)。
