### ISSUE TITLE
今天数据没有返回最新的截止到现在2020年03月09日11:03:10

### ISSUE THREAD

**Issue by crazyYG** [BlankerL/DXY-2019-nCoV-Crawler#73]
今天数据没有返回最新的截止到现在2020年03月09日11:03:10
接口：https://lab.isaaclin.cn/nCoV/api/overall?latest=1
服务停了？

**Comment by crazyYG** [comment]
@BlankerL    API 服务出问题了吗？

**Comment by BlankerL** [comment]
感谢反馈，不是API的问题，是丁香园不知道出于何种原因，屏蔽了目前正在使用的这个UserAgent，我更换了UserAgent之后已经正常运行了。
