### ISSUE TITLE
丁香医生的疑似确诊已改变

### ISSUE THREAD

**Issue by SupremacyX** [BlankerL/DXY-2019-nCoV-Crawler#74]
丁香医生的疑似确诊已消失，变为境外输入。

**Comment by BlankerL** [comment]
感谢反馈。

比较搞笑的是丁香园没有改变字段名称，仍然沿用的suspectedCount来表示境外输入数据。我认为丁香园应该会在近期修改字段名称，字段名称统一之后我会一并处理所有历史数据。

我会把这个信息列在API文档中，方便大家参考。

非常感谢！
