### ISSUE TITLE
关于update时间格式问题

### ISSUE THREAD

**Issue by yhli097** [BlankerL/DXY-2019-nCoV-Crawler#75]
在尝试绘制时间序列图像时， 我用到
https://lab.isaaclin.cn/nCoV/api/area?latest=0&province=湖北省
结果得到的updateTime有12位数字 例如 "1583923790822"
我想了解一下这个日期的格式 以便转为直观的时间

以及在搜索时 除了 province=湖北省 请问有没有用英文字母搜索的方法
感激不尽！

**Comment by BlankerL** [comment]
关于时间，可以参考#8
目前按省份获取仅支持中文，我会在近期加上英文的版本。
感谢建议。

**Comment by yhli097** [comment]
好的 问题解决了 谢谢！

**Comment by BlankerL** [comment]
已经支持通过/nCoV/api/area?provinceEng?=<English Name>，使用英文名称获取城市列表，具体使用方式请参考[API文档](https://lab.isaaclin.cn/nCoV/en)。

**Comment by yhli097** [comment]
太感谢了！解决的很及时 我就不用考虑怎么把英文转成中文了
万分感谢！

**Comment by BlankerL** [comment]
> 太感谢了！解决的很及时 我就不用考虑怎么把英文转成中文了
> 万分感谢！

谢谢支持！考虑到可能很多人会有这个问题，就先解决了😊
具体的英文城市列表可以通过/nCoV/api/provinceName?lang=en获取，也是新增的接口。
