### ISSUE TITLE
能否返回某个国家各个省/州/市的详细数据

### ISSUE THREAD

**Issue by haixiaodai** [BlankerL/DXY-2019-nCoV-Crawler#76]
现在查询澳大利亚返回的是澳大利亚的总确诊数
能否返回更详细的澳大利亚各个州的确诊数

**Comment by BlankerL** [comment]
不能，抱歉。目前丁香园并没有统计具体的各州数据，或许在澳洲有额外的机构在对这部分数据进行统计，可以查询相关机构。
