### ISSUE TITLE
03.15 丁香医生网页源代码似乎有更新

### ISSUE THREAD

**Issue by HgS318** [BlankerL/DXY-2019-nCoV-Crawler#78]
3.15下午发现数据爬不动了，看了下网页源代码好像是有一些更新，把解析信息的代码做了如下更改，目前可用

            overall_information = re.search(r'(\{"id".*\}\})\}', str(soup.find('script', attrs={'id': 'getStatisticsService'})))
            if overall_information:
                self.overall_parser(overall_information=overall_information)

            province_information = re.search(r'\[(.*?)\]', str(soup.find('script', attrs={'id': 'getListByCountryTypeService1undefined'})))
            if province_information:
                self.province_parser(province_information=province_information)

            area_information = re.search(r'\[(.*)\]', str(soup.find('script', attrs={'id': 'getAreaStat'})))
            if area_information:
                self.area_parser(area_information=area_information)

            abroad_information = re.search(r'\[(.*)\]', str(soup.find('script', attrs={'id': 'getListByCountryTypeService2undefined'})))
            if abroad_information:
                self.abroad_parser(abroad_information=abroad_information)

            news = re.search(r'\[(.*?)\]', str(soup.find('script', attrs={'id': 'getTimelineServiceundefined'})))
            if news:
                self.news_parser(news=news)

            rumors = re.search(r'\[(.*?)\]', str(soup.find('script', attrs={'id': 'getIndexRumorList'})))
            if rumors:
                self.rumor_parser(rumors=rumors)

**Comment by itachiluan** [comment]
最新的commit已经出来了
cdd216f40328a9767aab90d14f6e1dd8f560f150
