### ISSUE TITLE
使用R将13位时间转换为时间出现故障

### ISSUE THREAD

**Issue by yuanzhoulvpi2017** [BlankerL/DXY-2019-nCoV-Crawler#8]
我想问，你这个数据库保存的时间格式是什么样的，为什么获取的时间是13位格式的时间。
 > pro_data_temp$updateTime
 [1] 1580113184494
> as.POSIXct(pro_data_temp$updateTime, origin="1970-01-01 00:00:00")
 [1] "52041-10-17 09:01:34 CST"

**Comment by BlankerL** [comment]
抱歉，我对R的了解比较少，你的代码应该是转换10位时间戳的。
可以尝试把时间除以1000取整，变成10位时间戳再进行转换。
10位时间戳精度为秒，13位时间戳精度为毫秒。

**Comment by yuanzhoulvpi2017** [comment]
感谢，已经解决了，代码如下：
`as.POSIXct(pro_data_temp$updateTime/1000, origin="1970-01-01 00:00:00")`
