### ISSUE TITLE
也写了一个DXY-COVID-19-Data数据显示页面，增加了很多同类型显示网站没有的东西

### ISSUE THREAD

**Issue by zyq5945** [BlankerL/DXY-2019-nCoV-Crawler#80]
比如各省份和市区的详细的病例数，康复数，死亡数，在治数（正在治疗的数量的缩写，即累计病例数减去康复数与死亡数），康复率，死亡率和在治率等数据按日期发展的详细情况显示，还能对各省份和市区的数据进行对比，甚至是省份与市区的数据对比，方便发现一些疾病规律，并使用了Boltzmann模型对康复情况进行了数据仿真，也使用简单的一次线性模型对死亡情况进行了数据仿真，可以在页面调整仿真参数，并查看修改参数后的仿真结果。

https://zyq5945.github.io/diseasedataanalysis/overview.html

话说@BlankerL你没有爬国际数据吗？要是有的话能不能也发布一个数据仓库。

**Comment by zyq5945** [comment]
国内用户用这个地址可能快一些：

https://zyq5945.gitee.io/diseasedataanalysis/overview.html?DataUrl=https://zyq5945.gitee.io/dxy-covid-19-data-arrange-djson/data

**Comment by BlankerL** [comment]
感谢支持。

关于国际数据：BlankerL/DXY-COVID-19-Data#9
