### ISSUE TITLE
/nCoV/api/news接口返回的全为英文数据

### ISSUE THREAD

**Issue by weixinbao** [BlankerL/DXY-2019-nCoV-Crawler#86]
丁香园页面有变化。新闻news的爬虫需要把getTimelineService2改成getTimelineServiceundefined

**Comment by BlankerL** [comment]
感谢通知，我在 #82 [评论](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/82#issuecomment-600024230)中提到了这个问题，目前更新已经推送到GitHub，但是我暂时没有时间更新后端数据返回，大约在今晚11:00之后更新。

**Comment by weixinbao** [comment]
收到，辛苦！

**Comment by BlankerL** [comment]
已经上线，可以通过变量名指定中英文。具体使用方式可以参考[文档](https://lab.isaaclin.cn/nCoV/zh)。

更新：所有在丁香园返回数据变动期间遗漏的数据也已经补全。
