### ISSUE TITLE
关于增加新的数据类型（疫情地区数据）的建议

### ISSUE THREAD

**Issue by WH-2099** [BlankerL/DXY-2019-nCoV-Crawler#88]
高德地图与新华社客户端合作的[**疫情地区地图**](https://cache.amap.com/activity/partner/plague-map/index.html)收集了**新冠患者曾活动场所**
![source](https://user-images.githubusercontent.com/24429314/76988622-f4614580-697f-11ea-8b9a-0105720a3b64.png)
根据其声明，**只采用了各地卫健委的官方数据**，可信度及精确度较高，有一定的研究价值
建议加入数据仓库收录
我的简陋项目可供参考https://github.com/WH-2099/COVID-19-outbreak_area_data

最后，感谢您2个多月来的辛劳:+1::+1::+1:

**Comment by BlankerL** [comment]
感谢支持！

我也希望数据都是卫建委官方数据，如果你的数据来源可靠并且爬虫稳定，我可以直接将本项目添加至README文件中，并且将本issue置顶，让更多有需要的人知道，我就不重复造轮子啦～

**Comment by BlankerL** [comment]
我已经fork你的项目，最迟会在周末读完你的代码，如果没有问题的话我就直接把这个issue置顶。

**Comment by WH-2099** [comment]
谢谢！
关于数据：在6500+条中我随机抽选了10条做了验证，都能从各地卫健委找到对应官方发布。
关于代码：目前这个版本的代码是为了赶时间做出来的，问题还比较多，今明两天我会依照您的Crawler风格作以修改，最迟本周末我以pull request的方式作并入吧。

**Comment by BlankerL** [comment]
感谢，我已经看到您的pull request了，在明天或者后天会读一下，如果没问题就merge～
这两天比较忙，十分抱歉🙏
