### ISSUE TITLE
可以将这些中国数据共享给covid19_scenarios项目吗

### ISSUE THREAD

**Issue by Troy-Yang** [BlankerL/DXY-2019-nCoV-Crawler#90]
刚看到的项目，来自一个瑞士的大学，主要侧重于疫情数据模型的研究，现在还没看到中国数据的集成

https://github.com/neherlab/covid19_scenarios
https://github.com/neherlab/covid19_scenarios_data

**Comment by Troy-Yang** [comment]
简单网上收集了下，中国甚至世界的数据，下面有些地址也提供：

https://file1.dxycdn.com/2020/0315/383/3402160527840261656-135.json
https://interface.sina.cn/news/wap/fymap2020_data.d.json 
https://c.m.163.com/ug/api/wuhan/app/data/list-total?t=316952387169

**Comment by BlankerL** [comment]
这似乎是他们自己科研模型的可视化效果，并没有使用疫情数据。

本项目是疫情的时间序列数据爬虫和数据仓库，并没有做任何可视化项目。

**Comment by Troy-Yang** [comment]
是的，我看你这个项目https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/csv 下的数据就是那个项目所需要的可以用来分析的，刚好你是把中国的这些数据收集起来了，也是每日更新的

他们那边可以写个简单的python脚本去生成他们的模型数据，只是我不会python，这里已经有几个国家，包括美国的数据采集，https://github.com/neherlab/covid19_scenarios_data/tree/master/parsers

**Comment by BlankerL** [comment]
我看到你在他们的Issue里面发的内容了，他们可以直接使用数据，这个项目使用的是MIT协议。

**Comment by Troy-Yang** [comment]
好的，谢谢，可能最近没时间做。顺便说下，你这个项目很不错
