### ISSUE TITLE
self.db[collection].find_one(data) 方法报错

### ISSUE THREAD

**Issue by liguobao** [BlankerL/DXY-2019-nCoV-Crawler#93]
def find_one(self, collection, data=None):
        return self.db[collection].find_one(data)

 
return decode_all(data, codec_options)
bson.errors.InvalidBSON: 'utf-8' codec can't decode bytes in position 1907-1908: invalid continuation byte

**Comment by BlankerL** [comment]
看起来是数据库里存储的数据编码的问题。如果你在自己部署爬虫，可以详细说一下你改动了哪些内容。API的生产环境用的就是这一套代码，没有任何问题。

**Comment by liguobao** [comment]
没有改动的，除非我的DB设置不对。
不过我其他的程序用DB都挺正常的。

**Comment by BlankerL** [comment]
看报错的问题，应该是数据没有办法用UTF-8解码了，可以检查一下数据库里，这个字符串是不是有什么特殊的字符。
