### ISSUE TITLE
前端react框架调用api时常503的问题

### ISSUE THREAD

**Issue by QiaowenYoung** [BlankerL/DXY-2019-nCoV-Crawler#95]
发现在调用area和provinceName这两个api的时候总是503，可以说从未成功过。使用react框架，调用方法就是fetch(url).then(res => res.json()).then(data => {//处理data})。不知道为什么会这样。

**Comment by BlankerL** [comment]
麻烦参考#63，看看是不是这个问题。

**Comment by QiaowenYoung** [comment]
好的，谢谢
