### ISSUE TITLE
How do i find geo coordinates by locationId that present in the dataset

### ISSUE THREAD

**Issue by igor-litvinovich** [BlankerL/DXY-2019-nCoV-Crawler#97]
![image](https://user-images.githubusercontent.com/14150458/77856904-0d30ed00-7203-11ea-8717-407611157815.png)
is there any ways to find geo coordinates by the locationId like 430000?

**Comment by BlankerL** [comment]
If you would like to do visualization, there are many packages that can help you to deal with this. You only need to provide the countryName, provinceName (and cityName), and the packages will find the corresponding city for you. You do not need to get the coordinates on your own. 

Maybe you can try [ECharts](https://www.echartsjs.com/en/index.html), [D3](https://d3js.org/). 

I am not quite familiar with this field, maybe others will have better solution.
